name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: windows-2022

    steps:
      - uses: al-cheb/configure-pagefile-action@v1.4
        with:
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"

      - uses: actions/checkout@v4

      - name: Download Latest NNUE
        run: |
          curl -L -o nnue/latest.nnue https://github.com/official-stockfish/Stockfish/releases/latest/download/nn-eba324f53048.nnue

      - name: make
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}.exe NNUE_PATH=../nnue/latest.nnue && strip fairy-stockfish_${{ matrix.arch }}.exe

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}.exe largeboards=yes NNUE_PATH=../nnue/latest.nnue && strip fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-windows-${{ matrix.arch }}
          path: src/fairy-stockfish*.exe
          if-no-files-found: error
          compression-level: 9

  linux:
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Download Latest NNUE
        run: |
          wget -O nnue/latest.nnue https://github.com/official-stockfish/Stockfish/releases/latest/download/nn-eba324f53048.nnue

      - name: make
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} NNUE_PATH=../nnue/latest.nnue && strip fairy-stockfish_${{ matrix.arch }}

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }} largeboards=yes NNUE_PATH=../nnue/latest.nnue && strip fairy-stockfish-largeboards_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-linux-${{ matrix.arch }}
          path: src/fairy-stockfish*
          if-no-files-found: error
          compression-level: 9

  macos:
    strategy:
      matrix:
        arch: ["x86-64"]
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Download Latest NNUE
        run: curl -L -o nnue/latest.nnue https://github.com/official-stockfish/Stockfish/releases/latest/download/nn-eba324f53048.nnue

      - name: make
        run: cd src && make clean && make -j build COMP=clang ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} NNUE_PATH=../nnue/latest.nnue && strip fairy-stockfish_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-macos-${{ matrix.arch }}
          path: src/fairy-stockfish*
          if-no-files-found: error
          compression-level: 9

  macos-m1:
    strategy:
      matrix:
        arch: ["apple-silicon"]
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Download Latest NNUE
        run: curl -L -o nnue/latest.nnue https://github.com/official-stockfish/Stockfish/releases/latest/download/nn-eba324f53048.nnue

      - name: make
        run: cd src && make clean && make -j build COMP=clang ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }} NNUE_PATH=../nnue/latest.nnue && strip fairy-stockfish_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-macos-m1-${{ matrix.arch }}
          path: src/fairy-stockfish*
          if-no-files-found: error
          compression-level: 9
