name: Build Fairy-Stockfish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
      
      - name: Build Fairy-Stockfish
        run: |
          cd src
          make clean
          make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}.exe
          strip fairy-stockfish_${{ matrix.arch }}.exe
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-windows-${{ matrix.arch }}
          path: src/fairy-stockfish*.exe
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential
      
      - name: Build Fairy-Stockfish
        run: |
          cd src
          make clean
          make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}
          strip fairy-stockfish_${{ matrix.arch }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-linux-${{ matrix.arch }}
          path: src/fairy-stockfish*
          if-no-files-found: error

  build-macos:
    runs-on: macos-13
    strategy:
      matrix:
        arch: ["x86-64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Fairy-Stockfish
        run: |
          cd src
          make clean
          make -j build COMP=clang ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}
          strip fairy-stockfish_${{ matrix.arch }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-macos-${{ matrix.arch }}
          path: src/fairy-stockfish*
          if-no-files-found: error
